### ISSUE TITLE
Cannot read property 'SAMLResponse' of undefined

### ISSUE THREAD

**Issue by tinque** [tngan/samlify#177]
I use this code to parse the saml response with express : 
```(javascript)
router.post('/acs', (req, res, next) => {
	sp.parseLoginResponse(idp, 'post', req)
		.then((parseResult) => {
			console.log(parseResult);

			next();
		})
		.catch((err) => {
			log.error(err);
			res.type('txt');
			res.status(400).send(err.message);
		});
});
```
but I have the following error : 
```
 ERROR saml: Cannot read property 'SAMLResponse' of undefined
    TypeError: Cannot read property 'SAMLResponse' of undefined
        at ServiceProvider.<anonymous> (/node_modules/samlify/build/src/entity.js:247:46)
        at step (/node_modules/samlify/build/src/entity.js:40:23)
        at Object.next (/node_modules/samlify/build/src/entity.js:21:53)
        at /node_modules/samlify/build/src/entity.js:15:71
        at new Promise (<anonymous>)
        at __awaiter (/node_modules/samlify/build/src/entity.js:11:12)
        at ServiceProvider.Entity.genericParser (/node_modules/samlify/build/src/entity.js:170:16)
        at ServiceProvider.parseLoginResponse (/node_modules/samlify/build/src/entity-sp.js:93:21)
        at router.post (/app/router.js:48:5)
        at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
        at next (/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
        at /node_modules/express/lib/router/index.js:281:22
        at param (/node_modules/express/lib/router/index.js:354:14)
        at param (/node_modules/express/lib/router/index.js:365:14)
```

**Comment by tngan** [comment]
@tinque You can check this #156 for more information.

**Comment by tinque** [comment]
Sorry i didn't find this issue. Thanks a lot for your answer !

**Comment by tngan** [comment]
@tinque In fact, feel free to reopen this issue or extend the discussion in #156 if you have encountered further questions.
