### ISSUE TITLE
Investigate the stability of build

### ISSUE THREAD

**Issue by tngan** [tngan/samlify#200]
![image](https://user-images.githubusercontent.com/10245912/46020323-acf25400-c110-11e8-902c-c1b7683d066f.png)

It sometimes doesn't pass through the build because of the failure in schema validation.

**Comment by tngan** [comment]
```
Error: A JNI error has occurred, please check your installation and try again
Exception 
in thread "main" 
Error: A JNI error has occurred, please check your installation and try again
Exception 
in thread "main" 
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by tngan** [comment]
I have figured out why it happens. The validator library is not shipped with compiled class file, and the tests are running concurrently with ava. When `yarn test` is running, there is no compiled class file initially, therefore, for each test, it will spawn a `javac support/XMLValidator.java` command inside that library, so that the validator won't work at all.
