### ISSUE TITLE
SyntaxError when using 'javac' SAML_VALIDATOR

### ISSUE THREAD

**Issue by JustinBeaudry** [tngan/samlify#247]
```javascript
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
```

**Comment by tngan** [comment]
Which node.js version are you using ?

**Comment by tngan** [comment]
v2.6.0 is released on npm. Feel free to reopen if needed.
