### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by puravin** [tngan/samlify#249]
Getting the following error:
`Couldn't find package "@passify/xml-encryption@^0.11.1" required by "samlify" on the "npm" registry.`

**Comment by tngan** [comment]
@puravin What did you run ?

**Comment by puravin** [comment]
`yarn add samlify` @tngan

**Comment by tngan** [comment]
@puravin Are you by chance having any network issue, say blocked by firewall ? Also I want to know two things.

1) `yarn config get registry`, and
2) `yarn add samlify --verbose` to print out more detail about the error

**Comment by puravin** [comment]
I am not having any issues with the network.

These are the outputs from the above:
1) `https://registry.yarnpkg.com`

2)
```
verbose 4.065 Error: Couldn't find package "@passify/xml-encryption@^0.11.1" required by "samlify" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/puravin/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:727:66)
    at new MessageError (/Users/puravin/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/Users/puravin/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/Users/puravin/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:304:30)
    at /Users/puravin/.nvm/versions/node/v10.15.0/lib/node_modules/yarn/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Couldn't find package "@passify/xml-encryption@^0.11.1" required by "samlify" on the "npm" registry.
```

**Comment by tngan** [comment]
@puravin Please try `yarn --registry https://registry.npmjs.org`.

**Comment by puravin** [comment]
I am getting this on the console when running it on the project where I tried to install `samlify`

```
yarn install v1.13.0
1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
``

**Comment by tngan** [comment]
@puravin Try to remove `node_modules`, remove `samlify` from your `package.json`  and run

`SAML_VALIDATOR=javac yarn add samlify`

**Comment by tngan** [comment]
v2.6.0 is released on npm. Feel free to reopen if needed.
