### ISSUE TITLE
node v11 | node-gyp | libxmljs.o error npm

### ISSUE THREAD

**Issue by matth-c3** [tngan/samlify#265]
Hello, 

There is an error during the installation of samlify on node v11  on libxmljs.o. Not sure if it was reported already.

```
$ npm install samlify -d
npm info it worked if it ends with ok
npm info using npm@6.7.0
npm info using node@v11.13.0
npm http fetch GET 304 https://registry.npmjs.org/samlify 252ms (from cache)
npm timing stage:loadCurrentTree Completed in 1742ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 500ms
npm http fetch GET 304 https://registry.npmjs.org/node-rsa 88ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-xmllint 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xml 203ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/deflate-js 206ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xmldom 204ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xml-crypto 206ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/camelcase 208ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/xpath 208ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/libxml-xsd 210ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-forge 213ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@authenio%2fxml-encryption 1137ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/async 81ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ejs 88ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/libxmljs-mt 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 93ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/asn1 70ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2353ms
npm timing stage:loadIdealTree Completed in 3067ms
npm timing stage:generateActionsToTake Completed in 64ms
npm timing audit submit Completed in 740ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 741ms
npm timing audit body Completed in 1ms
npm timing action:extract Completed in 1388ms
npm timing action:finalize Completed in 32ms
npm timing action:refresh-package-json Completed in 48ms
npm info lifecycle async@2.6.2~preinstall: async@2.6.2
npm info lifecycle ejs@2.6.1~preinstall: ejs@2.6.1
npm info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
npm info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
npm info lifecycle libxmljs-mt@0.16.1~preinstall: libxmljs-mt@0.16.1
npm info lifecycle node-forge@0.7.6~preinstall: node-forge@0.7.6
npm info lifecycle asn1@0.2.3~preinstall: asn1@0.2.3
npm info lifecycle xmldom@0.1.27~preinstall: xmldom@0.1.27
npm info lifecycle xpath@0.0.27~preinstall: xpath@0.0.27
npm info lifecycle @authenio/xml-encryption@0.11.2~preinstall: @authenio/xml-encryption@0.11.2
npm info lifecycle deflate-js@0.2.3~preinstall: deflate-js@0.2.3
npm info lifecycle libxml-xsd@0.5.2~preinstall: libxml-xsd@0.5.2
npm info lifecycle node-rsa@0.4.2~preinstall: node-rsa@0.4.2
npm info lifecycle node-xmllint@1.0.0~preinstall: node-xmllint@1.0.0
npm info lifecycle camelcase@5.3.1~preinstall: camelcase@5.3.1
npm info lifecycle xml@1.0.1~preinstall: xml@1.0.1
npm info lifecycle xml-crypto@1.3.0~preinstall: xml-crypto@1.3.0
npm info lifecycle samlify@2.5.0~preinstall: samlify@2.5.0

> samlify@2.5.0 preinstall ..../core-system/node_modules/samlify
> make validator

make: Nothing to be done for `validator'.
npm timing action:preinstall Completed in 31ms
npm info linkStuff async@2.6.2
npm info linkStuff ejs@2.6.1
npm info linkStuff file-uri-to-path@1.0.0
npm info linkStuff bindings@1.5.0
npm info linkStuff libxmljs-mt@0.16.1
npm info linkStuff node-forge@0.7.6
npm info linkStuff asn1@0.2.3
npm info linkStuff xmldom@0.1.27
npm info linkStuff xpath@0.0.27
npm info linkStuff @authenio/xml-encryption@0.11.2
npm info linkStuff deflate-js@0.2.3
npm info linkStuff libxml-xsd@0.5.2
npm info linkStuff node-rsa@0.4.2
npm info linkStuff node-xmllint@1.0.0
npm info linkStuff camelcase@5.3.1
npm info linkStuff xml@1.0.1
npm info linkStuff xml-crypto@1.3.0
npm info linkStuff samlify@2.5.0
npm timing action:build Completed in 15ms
npm info lifecycle async@2.6.2~install: async@2.6.2
npm info lifecycle ejs@2.6.1~install: ejs@2.6.1
npm info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
npm info lifecycle bindings@1.5.0~install: bindings@1.5.0
npm info lifecycle libxmljs-mt@0.16.1~install: libxmljs-mt@0.16.1

> libxmljs-mt@0.16.1 install ..../core-system/node_modules/libxmljs-mt
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.13.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '....//core-system/node_modules/libxmljs-mt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '..../.node-gyp/11.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=..../.node-gyp/11.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=..../.node-gyp/11.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=..../core-system/node_modules/libxmljs-mt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc:69:17: error: no member named 'IsDead' in 'v8::V8'
    if (v8::V8::IsDead())
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ..../tcore-system/node_modules/libxmljs-mt
gyp ERR! node -v v11.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm info lifecycle libxmljs-mt@0.16.1~install: Failed to exec install script
npm info lifecycle node-forge@0.7.6~install: node-forge@0.7.6
npm info lifecycle asn1@0.2.3~install: asn1@0.2.3
npm info lifecycle xmldom@0.1.27~install: xmldom@0.1.27
npm info lifecycle xpath@0.0.27~install: xpath@0.0.27
npm info lifecycle @authenio/xml-encryption@0.11.2~install: @authenio/xml-encryption@0.11.2
npm info lifecycle deflate-js@0.2.3~install: deflate-js@0.2.3
npm info lifecycle node-rsa@0.4.2~install: node-rsa@0.4.2
npm info lifecycle node-xmllint@1.0.0~install: node-xmllint@1.0.0
npm info lifecycle camelcase@5.3.1~install: camelcase@5.3.1
npm info lifecycle xml@1.0.1~install: xml@1.0.1
npm info lifecycle xml-crypto@1.3.0~install: xml-crypto@1.3.0
npm info lifecycle samlify@2.5.0~install: samlify@2.5.0
npm timing action:install Completed in 3029ms
npm info lifecycle async@2.6.2~postinstall: async@2.6.2
npm info lifecycle ejs@2.6.1~postinstall: ejs@2.6.1
npm info lifecycle file-uri-to-path@1.0.0~postinstall: file-uri-to-path@1.0.0
npm info lifecycle bindings@1.5.0~postinstall: bindings@1.5.0
npm info lifecycle node-forge@0.7.6~postinstall: node-forge@0.7.6
npm info lifecycle asn1@0.2.3~postinstall: asn1@0.2.3
npm info lifecycle xmldom@0.1.27~postinstall: xmldom@0.1.27
npm info lifecycle xpath@0.0.27~postinstall: xpath@0.0.27
npm info lifecycle @authenio/xml-encryption@0.11.2~postinstall: @authenio/xml-encryption@0.11.2
npm info lifecycle deflate-js@0.2.3~postinstall: deflate-js@0.2.3
npm info lifecycle node-rsa@0.4.2~postinstall: node-rsa@0.4.2
npm info lifecycle node-xmllint@1.0.0~postinstall: node-xmllint@1.0.0
npm info lifecycle camelcase@5.3.1~postinstall: camelcase@5.3.1
npm info lifecycle xml@1.0.1~postinstall: xml@1.0.1
npm info lifecycle xml-crypto@1.3.0~postinstall: xml-crypto@1.3.0
npm info lifecycle samlify@2.5.0~postinstall: samlify@2.5.0
npm timing action:postinstall Completed in 5ms
npm timing stage:executeActions Completed in 4562ms
npm timing stage:rollbackFailedOptional Completed in 428ms
npm timing stage:runTopLevelLifecycles Completed in 10025ms
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: libxmljs-mt@0.16.1 (node_modules/libxmljs-mt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: libxmljs-mt@0.16.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ samlify@2.5.0
added 16 packages from 39 contributors and audited 6905 packages in 10.425s
found 0 vulnerabilities

npm timing npm Completed in 10786ms
npm info ok 
```

Thanks

**Comment by AngelMsger** [comment]
Because the dependency [libxml-xsd](https://github.com/albanm/node-libxml-xsd/issues/29) is not active maintained which cannot be compiled on node version higher than 10 😑.

**Comment by feugy** [comment]
@tngan, by default,  NPM is fetching [optional dependencies](https://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html). It simply does not complain in case they cannot be fetched (or compiled).

Could it be possible to use [peer dependencies](https://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html) instead? 

So users could have the choice to install xml-encryption, libxml-xsd or node-xmllint, without having NPM downloading (and compiling) all of them.

**Comment by virginc** [comment]
Having this same issue... how has everyone else fixed it?

**Comment by matth-c3** [comment]
> @tngan, by default, NPM is fetching [optional dependencies](https://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html). It simply does not complain in case they cannot be fetched (or compiled).
> 
> Could it be possible to use [peer dependencies](https://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html) instead?
> 
> So users could have the choice to install xml-encryption, libxml-xsd or node-xmllint, without having NPM downloading (and compiling) all of them.

@tngan  is it suitable for you to proceed like that ?

Thanks

**Comment by tngan** [comment]
@AngelMsger  @virginc  @feugy  @matth-c3 Let's continue the discussion in #274.

**Comment by tngan** [comment]
Please try the latest v2.6.0-rc1, we have a new implementation on how to make use of validator module.

**Comment by tngan** [comment]
v2.6.0 is released on npm. Feel free to reopen if needed.
