### ISSUE TITLE
Samlify cannot parse the idp xml

### ISSUE THREAD

**Issue by hassanNS** [tngan/samlify#266]
I am getting this error with the following error stack:
```
got to sso/acs err:  TypeError: Cannot read property 'validate' of null
2019-04-19T20:55:04.674409+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/samlify/build/src/libsaml.js:528:54)
2019-04-19T20:55:04.674411+00:00 app[web.1]:     at step (/app/node_modules/samlify/build/src/libsaml.js:37:23)
2019-04-19T20:55:04.674414+00:00 app[web.1]:     at Object.next (/app/node_modules/samlify/build/src/libsaml.js:18:53)
2019-04-19T20:55:04.674416+00:00 app[web.1]:     at /app/node_modules/samlify/build/src/libsaml.js:12:71
2019-04-19T20:55:04.674418+00:00 app[web.1]:     at new Promise (<anonymous>)
2019-04-19T20:55:04.674420+00:00 app[web.1]:     at __awaiter (/app/node_modules/samlify/build/src/libsaml.js:8:12)
2019-04-19T20:55:04.674422+00:00 app[web.1]:     at Object.isValidXml (/app/node_modules/samlify/build/src/libsaml.js:522:20)
2019-04-19T20:55:04.674424+00:00 app[web.1]:     at /app/node_modules/samlify/build/src/flow.js:157:60
2019-04-19T20:55:04.674426+00:00 app[web.1]:     at step (/app/node_modules/samlify/build/src/flow.js:32:23)
2019-04-19T20:55:04.674427+00:00 app[web.1]:     at Object.next (/app/node_modules/samlify/build/src/flow.js:13:53)
```

What is this error supposed to mean? My idp file is set up properly and so is my sp file, but samlify still cannot parse it. The post response from my idp that I am getting back is a success as well.

**Comment by moraleslevi** [comment]
I just started receiving this error as well. Recently updated to v2.5.0 to address the xml schema validation requirements, but I'm going to revert to the previous version to see if that fixes it.

**Comment by hassanNS** [comment]
I know the problem. It's because samlify could not load in any xml validators. It expects at least one of 3 validators as per the code in src/schema-validator.ts

```
enum SchemaValidators {
  JAVAC = '@authenio/xsd-schema-validator',
  LIBXML = 'libxml-xsd',
  XMLLINT = 'node-xmllint'
}
```

**Comment by hassanNS** [comment]
You need to install at least one of those using npm. I'm not sure why samlify doesn't do this automatically when you install it. I'm also not sure why there couldn't be an error in the code called `failed to load validator` if a validator library is not found.

**Comment by tngan** [comment]
@hassanNS It is supposed to install one of the packages automatically. Would you like to let us know what is node, npm, yarn version.

https://github.com/tngan/samlify/pull/259

**Comment by mobilestar2015** [comment]
I am not getting an error but it doesn't parse idp metadata from a file.

**Comment by tngan** [comment]
@mobilestar2015 Any code snippet ? It's hard for me to do further investigation from a single sentence.

**Comment by tngan** [comment]
Please reopen this thread if needed. There is no update since long time ago.
