### ISSUE TITLE
ERR_IDP_METADATA_MISSING_SINGLE_SIGN_ON_SERVICE

### ISSUE THREAD

**Issue by SoodS** [tngan/samlify#341]
I am trying to pass my IDP metadata URL to Identityprovider but it is not recognizing that.

```js
const idp = new saml.IdentityProvider({
    entityID: 'https://somedomain.com/fed/idp/metadata',
});
```

```
Error
DIR_PATH/node_modules/samlify/build/src/metadata-idp.js:75
                throw new Error('ERR_IDP_METADATA_MISSING_SINGLE_SIGN_ON_SERVICE');
                ^

Error: ERR_IDP_METADATA_MISSING_SINGLE_SIGN_ON_SERVICE
    at new IdpMetadata (DIR_PATH/node_modules/samlify/build/src/metadata-idp.js:75:23)
    at Object.default_1 [as default] (DIR_PATH/node_modules/samlify/build/src/metadata-idp.js:30:12)
    at IdentityProvider.Entity (DIR_PATH/node_modules/samlify/build/src/entity.js:53:57)
    at new IdentityProvider (DIR_PATH/node_modules/samlify/build/src/entity-idp.js:107:24)
    at new default_1 (DIR_PATH/node_modules/samlify/build/src/entity-idp.js:78:12)
```

**Comment by tngan** [comment]
@SoodS Thank you for your question. samlify won't download the metadata for you. You can see [this](https://samlify.js.org/#/idp) for the guideline for creating an IDP.

**Comment by SoodS** [comment]
Thanks @tngan  for this update. 

In documentation under the advance section, it was mentioned that you can fetch IDP metadata from Url. 
 [See this](https://samlify.js.org/#/idp-configuration) 

This is what I am trying to do here.

const idp = new IdentityProvider({
  // required
  entityID: 'http://hello-saml-idp.com/metadata',
  // optional parameters listed below
});

**Comment by tngan** [comment]
@SoodS In the documentation, it doesn't mention that the metadata will be fetched remotely for you. Instead, by putting those required/optional properties, samlify will generate the metadata for you. 

In fact, `entityID` just refers to the attribute (same name) of `EntityDescriptor` tag in the metadata.

```
You can either choose to import from metadata plus optional parameters, 
or defined properties plus optional parameters.
```

```js
const idp = new IdentityProvider({ ... });
idp.getMetadata();
```

The example used in the documentation might confuse you a bit, I will modify it later on.

**Comment by tngan** [comment]
@SoodS Is there any update on this ticket?

**Comment by OscarJVD** [comment]
Hello @tngan,
I've this error: ERR_IDP_METADATA_MISSING_SINGLE_SIGN_ON_SERVICE
And I'm trying to use sp private key and the idp public cert to make the SAML connection with my own IDP already tried with another SP made with passport-saml. I'd like to know if is possible to achieve this connection.

Thanks and greats

**Comment by brunoj** [comment]
Hey all,

I'm getting the same error under different circumstances. I'm trying to use Microsoft's Entra as IdP. For this purpose, I've registered an application and downloaded the associated FederationMetadata.xml (from https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/FederationMetadata/2007-06/FederationMetadata.xml).

However, when I do the following, as per documentation:

```
const idp = saml.IdentityProvider({
  metadata: fs.readFileSync('./FederationMetadata.xml')
});
```

I receive the error:
```

/srv/test_saml/node_modules/samlify/build/src/metadata-idp.js:105
                throw new Error('ERR_IDP_METADATA_MISSING_SINGLE_SIGN_ON_SERVICE');
                ^

Error: ERR_IDP_METADATA_MISSING_SINGLE_SIGN_ON_SERVICE
    at new IdpMetadata (/srv/test_saml/node_modules/samlify/build/src/metadata-idp.js:105:23)
    at default_1 (/srv/test_saml/node_modules/samlify/build/src/metadata-idp.js:47:12)
    at IdentityProvider.Entity (/srv/test_saml/node_modules/samlify/build/src/entity.js:79:62)
    at new IdentityProvider (/srv/test_saml/node_modules/samlify/build/src/entity-idp.js:128:23)
    at Object.default_1 [as IdentityProvider] (/srv/test_saml/node_modules/samlify/build/src/entity-idp.js:86:12)
    at Object.<anonymous> (/srv/test_saml/saml.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```


What am I doing wrong?

**Comment by ikoif** [comment]
For anyone who sees this, I fixed my issue by debugging the source code. After learning more about this error, I don't think everyone's reason for having this error thrown would be the same. 

I suggest trying the following:

1. Go to `/node_modules/samlify/build/src/metadata-idp.js:105:23` (this would be relative to the project folder)
2. Add a `console.log(meta)` after the `const isFile ...`:
  ```js
     const isFile = isString(meta) || meta instanceof Buffer;
     console.log(meta);
  ```
3. Check what's in the `meta` argument and try to diagnose your issue this way.

I hope this helps, good luck 🍀

**Comment by tngan** [comment]
This is intentional behaviour. Per saml-metadata §2.4.3, an `<IDPSSODescriptor>` MUST declare at least one `<SingleSignOnService>` endpoint — without it, no SP can initiate SSO against the IdP. samlify rejects construction in this case rather than silently emitting non-conforming metadata.

If you're constructing the IdP from a settings object (no metadata XML), supply at least one `singleSignOnService` entry:

```js
const idp = saml.IdentityProvider({
  entityID: 'https://idp.example.org/metadata',
  signingCert: readFileSync('./signing.cer'),
  singleSignOnService: [{
    Binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
    Location: 'https://idp.example.org/sso',
  }],
  // ...
});
```

See [`docs/idp-configuration.md`](https://samlify.js.org/#/idp-configuration) for the full option surface.

Closing as by-design. If you'd like the error message to point at this doc page directly, reopen and we can improve the wording.
