### ISSUE TITLE
[v2.7.4] Got Error: NO_SELECTED_CERTIFICATE when using keying information from external source

### ISSUE THREAD

**Issue by ebrurak** [tngan/samlify#382]
Hi,

I had before a signed request from SP using signing certificate from a database. And Samlify can send signed request to my IDP in POST binding. But when I update to 2.7.4 (and node v10), I got "Error: NO_SELECTED_CERTIFICATE" with my request.

>  stack: "Error: NO_SELECTED_CERTIFICATE
 at /root/git/samlify-dev/build/src/libsaml.js:290:31
 at Array.forEach (<anonymous>)
 at Object.verifySignature (/root/git/samlify-dev/build/src/libsaml.js:268:23)
 at /root/git/samlify-dev/build/src/flow.js:231:55
 at step (/root/git/samlify-dev/build/src/flow.js:33:23)
 at Object.next (/root/git/samlify-dev/build/src/flow.js:14:53)
 at fulfilled (/root/git/samlify-dev/build/src/flow.js:5:58)

I think it becomes from test in libsaml.js:verifySignature(xml: string, opts: SignatureVerifierOptions) function which is looking for X509Certificate absolutely from incoming signature node. So the certificate from "metadata" is ignored if it exists.

>
        verifySignature(xml: string, opts: SignatureVerifierOptions) {
             ....
             if (opts.metadata) {             
              const certificateNode = select(".//*[local-name(.)='X509Certificate']", signatureNode) as any;
              // certificate in metadata
              let metadataCert: any = opts.metadata.getX509Certificate(certUse.signing);
              // flattens the nested array of Certificates from each KeyDescriptor
              if (Array.isArray(metadataCert)) {
                 metadataCert = flattenDeep(metadataCert);
              } else if (typeof metadataCert === 'string') {
                 metadataCert = [metadataCert];
              }
              // normalise the certificate string
              metadataCert = metadataCert.map(utility.normalizeCerString);
              if (certificateNode.length === 0) {
                throw new Error('NO_SELECTED_CERTIFICATE');
              }
          ...
          }

Is there any problem?

Thanks in advance.

Best regards

**Comment by mashpie** [comment]
Exactly same to me and I can confirm it works after downgrade to 2.7.3. I have a lemonLDAP as IDP which is not providing CERTs as x509 within its metadata. To come around that I built up my own copy of metadata xml which is loaded to configure IDP:

```js
 /**
   * configure corresponding lemonLDAP as identity provider
   */
  const idp = saml.IdentityProvider({ metadata: samlIDPmetadata })
```

configured within `samlIDPmetadta`:

```xml
    <KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <X509Data>
          <X509Certificate>...</X509Certificate>
        </X509Data>
      </ds:KeyInfo>
    </KeyDescriptor>
```

provided by lemonLDAP:

```xml
    <KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:KeyValue>
          <RSAKeyValue xmlns="http://www.w3.org/2000/09/xmldsig#">
            <Modulus>...</Modulus>
            <Exponent>...</Exponent>
          </RSAKeyValue>
        </ds:KeyValue>
      </ds:KeyInfo>
    </KeyDescriptor>
```

**Comment by tngan** [comment]
@mashpie @ebrurak There is a fix in PR, I will take a look on it soon. https://github.com/tngan/samlify/pull/380

**Comment by eqqnqqn** [comment]
Hello Tony,

I would like to add a new point before you rollout the correction.
As you said it, certificate is not mandatory in request and thanks to your correction, samlify will fallback to the certificate in metadata.

However, in my use case, I don’t trust the certificate in request so
• I would like to use exclusively the certificate in metadata
• and so generate error if in case of signature verification is needed, only request certificate is available (if during registration for example of a client, I forgot to fill its certificate in metadata)

So it could be useful to have new parameter(s) in server configuration to define

    which certificate has the highest priority if both are present (in metadata and in request)
    and potentially if the use of this certificate is exclusive ( only this certificate is allowed (ie metadata) )

Thanks for your feedback. @tngan

Best regards.

**Comment by tngan** [comment]
Yes, we cannot trust the certificate from the SAML document either request or response. We cannot directly apply that certificate without verification, otherwise, it potentially bypasses the actual validation because a malicious action can be done easily by replacing with any certificate that used to sign the malicious document.

So we need some sort of protection for it. The specification doesn't require to include  certificate in the document.

The validation flow can be simplified to fulfill the common use cases including rolling basis.

The behaviour will be as follow:

1. If no certificate in metadata, throw error.
2. If there is certificate in document, see if it matches any one stated in the metadata.
3. No certificate in document and then iterate those stated in metadata to see if validation is passed.

Precedence option might not help because we still want to see if any certificate works for the validation. In other words, certificates put in metadata is always the source of truth.

Feel free to discuss it.

**Comment by mashpie** [comment]
So, metaData certificates encoded as X509Datashould get decoded. Currently it seems like those get ignored.

**Comment by eqqnqqn** [comment]
> 
> 
> Yes, we cannot trust the certificate from the SAML document either request or response. We cannot directly apply that certificate without verification, otherwise, it potentially bypasses the actual validation because a malicious action can be done easily by replacing with any certificate that used to sign the malicious document.
> 
> So we need some sort of protection for it. The specification doesn't require to include certificate in the document.
> 
> The validation flow can be simplified to fulfill the common use cases including rolling basis.
> 
> The behaviour will be as follow:
> 
>     1. If no certificate in metadata, throw error.
> 
>     2. If there is certificate in document, see if it matches any one stated in the metadata.
> 
>     3. No certificate in document and then iterate those stated in metadata to see if validation is passed.
> 
> 
> Precedence option might not help because we still want to see if any certificate works for the validation. In other words, certificates put in metadata is always the source of truth.
> 
> Feel free to discuss it.



Thanks Tony ! @tngan 
Here below my proposal as for point 2 of your proposition, the behaviour in case of no certificate matching is not detailed. 
 
In case of signature expected from client (sender of saml request),
1.	If no certificate in metadata, throw error.
2.	If there is certificate in document, see if it matches any one stated in the metadata. If yes, see if validation is passed, otherwise, throw error.
3.	No certificate in document and then iterate those stated in metadata to see if validation is passed.

In case of signature not expected from client (sender of saml request),
1.	Don’t take into account certificate in metadata or in document.
What do you think about it? If convenient for you, when could it be deployed ?

**Comment by ndesimone** [comment]
We're experiencing the same problem (`NO_SELECTED_CERTIFICATE`) during client integration with PingFederate.

**Comment by SDepn** [comment]
Any news on this issue? I am also running into the same issue and the only fix we have is downgrading to 2.7.3.

**Comment by tngan** [comment]
This was filed against `2.7.4` (2020). The certificate resolution path in `libsaml.verifySignature` has been rewritten several times since — most relevantly to support rolling certificates (#368) and to cross-check certificates declared in metadata against those embedded in the response. The "external keying" scenarios should now resolve via `metadata.getX509Certificate('signing')` returning either a string or array of strings.

Please retest on `samlify@^2.13.0`. If you can still reproduce, please reopen with the current samlify version, your SP/IdP setup, and the response you're trying to verify (redacted as needed).

Closing as stale; the underlying code is no longer the same.
