### ISSUE TITLE
ERR_INVALID_ARG_TYPE: url must be type string, received object.

### ISSUE THREAD

**Issue by tuckerzb** [tngan/samlify#468]
Error Text:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:170:3)
    at Object.urlParse (url.js:157:13)
    at buildRedirectURL (/Users/tuckerz/complyauto-privacy/node_modules/samlify/src/binding-redirect.ts:55:25)
    at Object.loginRequestRedirectURL (/Users/tuckerz/complyauto-privacy/node_modules/samlify/src/binding-redirect.ts:116:16)
    at ServiceProvider.createLoginRequest (/Users/tuckerz/complyauto-privacy/node_modules/samlify/src/entity-sp.ts:71:32)
    at /Users/tuckerz/complyauto-privacy/dist/apps/api-dealer/webpack:/libs/api/data-api-dealer/src/lib/api/graphql/auth/user/mutations.ts:94:42
    at Generator.next (<anonymous>)
    at /Users/tuckerz/complyauto-privacy/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
```

Full Code:
```
  const samlIdp = samlify.IdentityProvider({
    metadata: idpMetadata,
    isAssertionEncrypted: false,
    // messageSigningOrder: 'encrypt-then-sign',
    wantLogoutRequestSigned: false,
  });

  const samlSp = samlify.ServiceProvider({
    entityID: 'https://dealer.complyauto.com',
    authnRequestsSigned: false,
    wantAssertionsSigned: false,
    wantMessageSigned: false,
    wantLogoutResponseSigned: false,
    wantLogoutRequestSigned: false,
    // the private key (.pem) use to sign the assertion;
    // privateKey: fs.readFileSync(__dirname + '/ssl/sign/privkey.pem'),
    // the private key pass;
    // privateKeyPass: 'VHOSp5RUiBcrsjrcAuXFwU1NKCkGA8px',
    // the private key (.pem) use to encrypt the assertion;
    // encPrivateKey: fs.readFileSync(__dirname + '/ssl/encrypt/privkey.pem'),
    isAssertionEncrypted: false,
    assertionConsumerService: [
      {
        Binding: samlify.Constants.namespace.binding.redirect,
        Location: 'http://localhost:4200/saml/acs',
      },
    ],
  });

  try {
    const { id, context } = await samlSp.createLoginRequest(
      samlIdp,
      'redirect'
    );
    console.log(context);
  } catch (error) {
    console.log(error);
  }
```

IdP Metadata:
```
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="http://www.okta.com/exk3t5ivf4oQ4GLNJ5d7">
<md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>.... CERTIFICATE</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://dev-3152560.okta.com/app/dev-3152560_samltest_1/exk3t5ivf4oQ4GLNJ5d7/sso/saml"/>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://dev-3152560.okta.com/app/dev-3152560_samltest_1/exk3t5ivf4oQ4GLNJ5d7/sso/saml"/>
</md:IDPSSODescriptor>
</md:EntityDescriptor>
```

I've found in other issues that this can present when you are trying to set the wrong kind of binding for the IdP metadata, but I don't that is the case here. 

Appreciate your hard work on this library!

**Comment by carsonwah** [comment]
Hi just tried your IDP metadata, it looks fine on my side.

My suggestion is to try debugging by adding some `console.log()` in `node_modules/samlify/build/src/binding-redirect.js`, to see what value is the url in runtime. I did it this way when using this library as well.

### Related code
Error line:
https://github.com/tngan/samlify/blob/1bf1eba492ab0249e49282eac16bfa1451e3c4a6/src/binding-redirect.ts#L55
Value is generated from:
https://github.com/tngan/samlify/blob/1bf1eba492ab0249e49282eac16bfa1451e3c4a6/src/binding-redirect.ts#L147

**Comment by tuckerzb** [comment]
@carsonwah Thank you for the reply! I've traced this issue through `sp.createLoginRequest`, to `loginRequestRedirectUrl`, to `buildRedirectUrl`, to `getSingleSignOnService` and it appears that the issue is that the IdP metadata is not being parsed. Here is the console output:

```
entityMeta: IdpMetadata {
    xmlString: 'https://dev-3152560.okta.com/app/exk3t5ivf4oQ4GLNJ5d7/sso/saml/metadata',
    meta: {
      wantAuthnRequestsSigned: undefined,
      singleSignOnService: {},
      entityDescriptor: null,
      entityID: undefined,
      sharedCertificate: null,
      certificate: {},
      singleLogoutService: [],
      nameIDFormat: null
    }
  }
```

The SP metadata is being parsed correctly, so I doubly unsure of why a) you and I are getting different results with the same metadata) and b) I am seeing different results locally between the IdP and SP. 

Will update this thread if I find a resolution.

**Comment by tuckerzb** [comment]
I'm going to go ahead and close this issue. I have not identified the issue here, but at this point, am confident it is user error and not an issue with the package. 

Thanks to all the maintainers for your work on samlify!
